services:
  - type: web
    name: gdi-data-governance
    env: node
    buildCommand: chmod +x ./scripts/build.sh && ./scripts/build.sh
    startCommand: chmod +x ./scripts/start.sh && ./scripts/start.sh
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: gdi-database
          property: connectionString

databases:
  - name: gdi-database
    databaseName: gdi_data_governance
    ipAllowList: []
    plan: starter